[theme]
primaryColor="#5a282a"
backgroundColor="#181916"
secondaryBackgroundColor="#383a37"
textColor="#d9ccbb"
font="sans serif"

#121210 #black #181916
#383a37 #green
#5a282a #red
#826056 #brown
#d9ccbb #cream